import type { Metadata } from "next";
import { Poppins, Alumni_Sans } from "next/font/google";
import "../assets/scss/main.scss";

// Define the Poppins font
const poppins = Poppins({
  weight: ["400", "600", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
  display: "swap",
});

// Define the Alumni Sans font
const alumniSans = Alumni_Sans({
  weight: ["400", "600", "700"],
  subsets: ["latin"],
  variable: "--font-alumni-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${alumniSans.variable}`}>
        {children}
      </body>
    </html>
  );
}
